@base = http://localhost:3000/tasks

POST {{base}}
Content-Type: application/json

{
    "title":"Hacer el baño"
}
###
PUT {{base}}/6a8dc1a563ee59fb7d0d78e1
Content-Type: application/json

{
    "done":true
}

###
DELETE {{base}}/6a8dc1a563ee59fb7d0d78e1